// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v5.29.5
// source: proto/hermes.proto

package hermespb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	HermesService_Notify_FullMethodName       = "/hermes.HermesService/Notify"
	HermesService_GetUIConfig_FullMethodName  = "/hermes.HermesService/GetUIConfig"
	HermesService_ReportChoice_FullMethodName = "/hermes.HermesService/ReportChoice"
	HermesService_Cancel_FullMethodName       = "/hermes.HermesService/Cancel"
	HermesService_List_FullMethodName         = "/hermes.HermesService/List"
)

// HermesServiceClient is the client API for HermesService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// HermesService manages notification lifecycles. The service daemon
// (hermes serve) implements this; CLI commands and UI subprocesses
// are clients.
type HermesServiceClient interface {
	// Notify sends a notification and blocks until the user responds,
	// the notification times out, or the deferral deadline expires.
	// Called by: hermes notify / hermes --config
	Notify(ctx context.Context, in *NotifyRequest, opts ...grpc.CallOption) (*NotifyResponse, error)
	// GetUIConfig returns the notification config for a UI subprocess.
	// Called by: the Wails UI process on startup.
	GetUIConfig(ctx context.Context, in *GetUIConfigRequest, opts ...grpc.CallOption) (*GetUIConfigResponse, error)
	// ReportChoice reports the user's button click or timeout from the UI.
	// Called by: the Wails UI process on user interaction.
	ReportChoice(ctx context.Context, in *ReportChoiceRequest, opts ...grpc.CallOption) (*ReportChoiceResponse, error)
	// Cancel cancels an active notification by ID.
	// Called by: hermes cancel <id>
	Cancel(ctx context.Context, in *CancelRequest, opts ...grpc.CallOption) (*CancelResponse, error)
	// List returns all active (pending/deferred) notifications.
	// Called by: hermes list
	List(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListResponse, error)
}

type hermesServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewHermesServiceClient(cc grpc.ClientConnInterface) HermesServiceClient {
	return &hermesServiceClient{cc}
}

func (c *hermesServiceClient) Notify(ctx context.Context, in *NotifyRequest, opts ...grpc.CallOption) (*NotifyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NotifyResponse)
	err := c.cc.Invoke(ctx, HermesService_Notify_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hermesServiceClient) GetUIConfig(ctx context.Context, in *GetUIConfigRequest, opts ...grpc.CallOption) (*GetUIConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUIConfigResponse)
	err := c.cc.Invoke(ctx, HermesService_GetUIConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hermesServiceClient) ReportChoice(ctx context.Context, in *ReportChoiceRequest, opts ...grpc.CallOption) (*ReportChoiceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReportChoiceResponse)
	err := c.cc.Invoke(ctx, HermesService_ReportChoice_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hermesServiceClient) Cancel(ctx context.Context, in *CancelRequest, opts ...grpc.CallOption) (*CancelResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CancelResponse)
	err := c.cc.Invoke(ctx, HermesService_Cancel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hermesServiceClient) List(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListResponse)
	err := c.cc.Invoke(ctx, HermesService_List_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HermesServiceServer is the server API for HermesService service.
// All implementations must embed UnimplementedHermesServiceServer
// for forward compatibility.
//
// HermesService manages notification lifecycles. The service daemon
// (hermes serve) implements this; CLI commands and UI subprocesses
// are clients.
type HermesServiceServer interface {
	// Notify sends a notification and blocks until the user responds,
	// the notification times out, or the deferral deadline expires.
	// Called by: hermes notify / hermes --config
	Notify(context.Context, *NotifyRequest) (*NotifyResponse, error)
	// GetUIConfig returns the notification config for a UI subprocess.
	// Called by: the Wails UI process on startup.
	GetUIConfig(context.Context, *GetUIConfigRequest) (*GetUIConfigResponse, error)
	// ReportChoice reports the user's button click or timeout from the UI.
	// Called by: the Wails UI process on user interaction.
	ReportChoice(context.Context, *ReportChoiceRequest) (*ReportChoiceResponse, error)
	// Cancel cancels an active notification by ID.
	// Called by: hermes cancel <id>
	Cancel(context.Context, *CancelRequest) (*CancelResponse, error)
	// List returns all active (pending/deferred) notifications.
	// Called by: hermes list
	List(context.Context, *ListRequest) (*ListResponse, error)
	mustEmbedUnimplementedHermesServiceServer()
}

// UnimplementedHermesServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedHermesServiceServer struct{}

func (UnimplementedHermesServiceServer) Notify(context.Context, *NotifyRequest) (*NotifyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Notify not implemented")
}
func (UnimplementedHermesServiceServer) GetUIConfig(context.Context, *GetUIConfigRequest) (*GetUIConfigResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUIConfig not implemented")
}
func (UnimplementedHermesServiceServer) ReportChoice(context.Context, *ReportChoiceRequest) (*ReportChoiceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReportChoice not implemented")
}
func (UnimplementedHermesServiceServer) Cancel(context.Context, *CancelRequest) (*CancelResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Cancel not implemented")
}
func (UnimplementedHermesServiceServer) List(context.Context, *ListRequest) (*ListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedHermesServiceServer) mustEmbedUnimplementedHermesServiceServer() {}
func (UnimplementedHermesServiceServer) testEmbeddedByValue()                       {}

// UnsafeHermesServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HermesServiceServer will
// result in compilation errors.
type UnsafeHermesServiceServer interface {
	mustEmbedUnimplementedHermesServiceServer()
}

func RegisterHermesServiceServer(s grpc.ServiceRegistrar, srv HermesServiceServer) {
	// If the following call panics, it indicates UnimplementedHermesServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&HermesService_ServiceDesc, srv)
}

func _HermesService_Notify_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NotifyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HermesServiceServer).Notify(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HermesService_Notify_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HermesServiceServer).Notify(ctx, req.(*NotifyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HermesService_GetUIConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUIConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HermesServiceServer).GetUIConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HermesService_GetUIConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HermesServiceServer).GetUIConfig(ctx, req.(*GetUIConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HermesService_ReportChoice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReportChoiceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HermesServiceServer).ReportChoice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HermesService_ReportChoice_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HermesServiceServer).ReportChoice(ctx, req.(*ReportChoiceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HermesService_Cancel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HermesServiceServer).Cancel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HermesService_Cancel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HermesServiceServer).Cancel(ctx, req.(*CancelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HermesService_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HermesServiceServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HermesService_List_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HermesServiceServer).List(ctx, req.(*ListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// HermesService_ServiceDesc is the grpc.ServiceDesc for HermesService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HermesService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "hermes.HermesService",
	HandlerType: (*HermesServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Notify",
			Handler:    _HermesService_Notify_Handler,
		},
		{
			MethodName: "GetUIConfig",
			Handler:    _HermesService_GetUIConfig_Handler,
		},
		{
			MethodName: "ReportChoice",
			Handler:    _HermesService_ReportChoice_Handler,
		},
		{
			MethodName: "Cancel",
			Handler:    _HermesService_Cancel_Handler,
		},
		{
			MethodName: "List",
			Handler:    _HermesService_List_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/hermes.proto",
}
