// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.5
// source: proto/hermes.proto

package hermespb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NotifyRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique notification ID. Auto-generated if empty.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// JSON-encoded NotificationConfig. The service deserializes it
	// to detect buttons, timeouts, and deferral settings.
	ConfigJson    []byte `protobuf:"bytes,2,opt,name=config_json,json=configJson,proto3" json:"config_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotifyRequest) Reset() {
	*x = NotifyRequest{}
	mi := &file_proto_hermes_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotifyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyRequest) ProtoMessage() {}

func (x *NotifyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hermes_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyRequest.ProtoReflect.Descriptor instead.
func (*NotifyRequest) Descriptor() ([]byte, []int) {
	return file_proto_hermes_proto_rawDescGZIP(), []int{0}
}

func (x *NotifyRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *NotifyRequest) GetConfigJson() []byte {
	if x != nil {
		return x.ConfigJson
	}
	return nil
}

type NotifyResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The user's response value (e.g. "restart", "defer_4h", "timeout:restart").
	Value string `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	// Exit code the CLI should use (mirrors cmd exit constants).
	ExitCode int32 `protobuf:"varint,2,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	// Human-readable error message, if any.
	Error         string `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotifyResponse) Reset() {
	*x = NotifyResponse{}
	mi := &file_proto_hermes_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotifyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyResponse) ProtoMessage() {}

func (x *NotifyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hermes_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyResponse.ProtoReflect.Descriptor instead.
func (*NotifyResponse) Descriptor() ([]byte, []int) {
	return file_proto_hermes_proto_rawDescGZIP(), []int{1}
}

func (x *NotifyResponse) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *NotifyResponse) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *NotifyResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type GetUIConfigRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Notification ID assigned by the service.
	NotificationId string `protobuf:"bytes,1,opt,name=notification_id,json=notificationId,proto3" json:"notification_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetUIConfigRequest) Reset() {
	*x = GetUIConfigRequest{}
	mi := &file_proto_hermes_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUIConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUIConfigRequest) ProtoMessage() {}

func (x *GetUIConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hermes_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUIConfigRequest.ProtoReflect.Descriptor instead.
func (*GetUIConfigRequest) Descriptor() ([]byte, []int) {
	return file_proto_hermes_proto_rawDescGZIP(), []int{2}
}

func (x *GetUIConfigRequest) GetNotificationId() string {
	if x != nil {
		return x.NotificationId
	}
	return ""
}

type GetUIConfigResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// JSON-encoded NotificationConfig for the UI to render.
	ConfigJson []byte `protobuf:"bytes,1,opt,name=config_json,json=configJson,proto3" json:"config_json,omitempty"`
	// Whether the user is still allowed to defer (deadline not passed, defers remaining).
	DeferralAllowed bool `protobuf:"varint,2,opt,name=deferral_allowed,json=deferralAllowed,proto3" json:"deferral_allowed,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetUIConfigResponse) Reset() {
	*x = GetUIConfigResponse{}
	mi := &file_proto_hermes_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUIConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUIConfigResponse) ProtoMessage() {}

func (x *GetUIConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hermes_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUIConfigResponse.ProtoReflect.Descriptor instead.
func (*GetUIConfigResponse) Descriptor() ([]byte, []int) {
	return file_proto_hermes_proto_rawDescGZIP(), []int{3}
}

func (x *GetUIConfigResponse) GetConfigJson() []byte {
	if x != nil {
		return x.ConfigJson
	}
	return nil
}

func (x *GetUIConfigResponse) GetDeferralAllowed() bool {
	if x != nil {
		return x.DeferralAllowed
	}
	return false
}

type ReportChoiceRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Notification ID this choice belongs to.
	NotificationId string `protobuf:"bytes,1,opt,name=notification_id,json=notificationId,proto3" json:"notification_id,omitempty"`
	// The value from the button click or timeout (e.g. "restart", "defer_4h", "timeout:restart").
	Value         string `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportChoiceRequest) Reset() {
	*x = ReportChoiceRequest{}
	mi := &file_proto_hermes_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportChoiceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportChoiceRequest) ProtoMessage() {}

func (x *ReportChoiceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hermes_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportChoiceRequest.ProtoReflect.Descriptor instead.
func (*ReportChoiceRequest) Descriptor() ([]byte, []int) {
	return file_proto_hermes_proto_rawDescGZIP(), []int{4}
}

func (x *ReportChoiceRequest) GetNotificationId() string {
	if x != nil {
		return x.NotificationId
	}
	return ""
}

func (x *ReportChoiceRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type ReportChoiceResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// True if the service accepted the choice (first responder wins).
	Accepted      bool `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReportChoiceResponse) Reset() {
	*x = ReportChoiceResponse{}
	mi := &file_proto_hermes_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReportChoiceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReportChoiceResponse) ProtoMessage() {}

func (x *ReportChoiceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hermes_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReportChoiceResponse.ProtoReflect.Descriptor instead.
func (*ReportChoiceResponse) Descriptor() ([]byte, []int) {
	return file_proto_hermes_proto_rawDescGZIP(), []int{5}
}

func (x *ReportChoiceResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

type CancelRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	NotificationId string                 `protobuf:"bytes,1,opt,name=notification_id,json=notificationId,proto3" json:"notification_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CancelRequest) Reset() {
	*x = CancelRequest{}
	mi := &file_proto_hermes_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelRequest) ProtoMessage() {}

func (x *CancelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hermes_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelRequest.ProtoReflect.Descriptor instead.
func (*CancelRequest) Descriptor() ([]byte, []int) {
	return file_proto_hermes_proto_rawDescGZIP(), []int{6}
}

func (x *CancelRequest) GetNotificationId() string {
	if x != nil {
		return x.NotificationId
	}
	return ""
}

type CancelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Found         bool                   `protobuf:"varint,1,opt,name=found,proto3" json:"found,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelResponse) Reset() {
	*x = CancelResponse{}
	mi := &file_proto_hermes_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelResponse) ProtoMessage() {}

func (x *CancelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hermes_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelResponse.ProtoReflect.Descriptor instead.
func (*CancelResponse) Descriptor() ([]byte, []int) {
	return file_proto_hermes_proto_rawDescGZIP(), []int{7}
}

func (x *CancelResponse) GetFound() bool {
	if x != nil {
		return x.Found
	}
	return false
}

type ListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRequest) Reset() {
	*x = ListRequest{}
	mi := &file_proto_hermes_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRequest) ProtoMessage() {}

func (x *ListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hermes_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRequest.ProtoReflect.Descriptor instead.
func (*ListRequest) Descriptor() ([]byte, []int) {
	return file_proto_hermes_proto_rawDescGZIP(), []int{8}
}

type ListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Notifications []*NotificationInfo    `protobuf:"bytes,1,rep,name=notifications,proto3" json:"notifications,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListResponse) Reset() {
	*x = ListResponse{}
	mi := &file_proto_hermes_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResponse) ProtoMessage() {}

func (x *ListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hermes_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListResponse.ProtoReflect.Descriptor instead.
func (*ListResponse) Descriptor() ([]byte, []int) {
	return file_proto_hermes_proto_rawDescGZIP(), []int{9}
}

func (x *ListResponse) GetNotifications() []*NotificationInfo {
	if x != nil {
		return x.Notifications
	}
	return nil
}

type NotificationInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Heading       string                 `protobuf:"bytes,2,opt,name=heading,proto3" json:"heading,omitempty"`
	State         string                 `protobuf:"bytes,3,opt,name=state,proto3" json:"state,omitempty"` // "pending", "deferred", "awaiting_response"
	DeferCount    int32                  `protobuf:"varint,4,opt,name=defer_count,json=deferCount,proto3" json:"defer_count,omitempty"`
	DeadlineUnix  int64                  `protobuf:"varint,5,opt,name=deadline_unix,json=deadlineUnix,proto3" json:"deadline_unix,omitempty"` // 0 = no deadline
	CreatedUnix   int64                  `protobuf:"varint,6,opt,name=created_unix,json=createdUnix,proto3" json:"created_unix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotificationInfo) Reset() {
	*x = NotificationInfo{}
	mi := &file_proto_hermes_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotificationInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotificationInfo) ProtoMessage() {}

func (x *NotificationInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hermes_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotificationInfo.ProtoReflect.Descriptor instead.
func (*NotificationInfo) Descriptor() ([]byte, []int) {
	return file_proto_hermes_proto_rawDescGZIP(), []int{10}
}

func (x *NotificationInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *NotificationInfo) GetHeading() string {
	if x != nil {
		return x.Heading
	}
	return ""
}

func (x *NotificationInfo) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *NotificationInfo) GetDeferCount() int32 {
	if x != nil {
		return x.DeferCount
	}
	return 0
}

func (x *NotificationInfo) GetDeadlineUnix() int64 {
	if x != nil {
		return x.DeadlineUnix
	}
	return 0
}

func (x *NotificationInfo) GetCreatedUnix() int64 {
	if x != nil {
		return x.CreatedUnix
	}
	return 0
}

type ListHistoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListHistoryRequest) Reset() {
	*x = ListHistoryRequest{}
	mi := &file_proto_hermes_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListHistoryRequest) ProtoMessage() {}

func (x *ListHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hermes_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListHistoryRequest.ProtoReflect.Descriptor instead.
func (*ListHistoryRequest) Descriptor() ([]byte, []int) {
	return file_proto_hermes_proto_rawDescGZIP(), []int{11}
}

type ListHistoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Records       []*HistoryEntry        `protobuf:"bytes,1,rep,name=records,proto3" json:"records,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListHistoryResponse) Reset() {
	*x = ListHistoryResponse{}
	mi := &file_proto_hermes_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListHistoryResponse) ProtoMessage() {}

func (x *ListHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hermes_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListHistoryResponse.ProtoReflect.Descriptor instead.
func (*ListHistoryResponse) Descriptor() ([]byte, []int) {
	return file_proto_hermes_proto_rawDescGZIP(), []int{12}
}

func (x *ListHistoryResponse) GetRecords() []*HistoryEntry {
	if x != nil {
		return x.Records
	}
	return nil
}

type HistoryEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Heading       string                 `protobuf:"bytes,2,opt,name=heading,proto3" json:"heading,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Source        string                 `protobuf:"bytes,4,opt,name=source,proto3" json:"source,omitempty"`
	ResponseValue string                 `protobuf:"bytes,5,opt,name=response_value,json=responseValue,proto3" json:"response_value,omitempty"`
	CreatedUnix   int64                  `protobuf:"varint,6,opt,name=created_unix,json=createdUnix,proto3" json:"created_unix,omitempty"`
	CompletedUnix int64                  `protobuf:"varint,7,opt,name=completed_unix,json=completedUnix,proto3" json:"completed_unix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HistoryEntry) Reset() {
	*x = HistoryEntry{}
	mi := &file_proto_hermes_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HistoryEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HistoryEntry) ProtoMessage() {}

func (x *HistoryEntry) ProtoReflect() protoreflect.Message {
	mi := &file_proto_hermes_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HistoryEntry.ProtoReflect.Descriptor instead.
func (*HistoryEntry) Descriptor() ([]byte, []int) {
	return file_proto_hermes_proto_rawDescGZIP(), []int{13}
}

func (x *HistoryEntry) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *HistoryEntry) GetHeading() string {
	if x != nil {
		return x.Heading
	}
	return ""
}

func (x *HistoryEntry) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *HistoryEntry) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *HistoryEntry) GetResponseValue() string {
	if x != nil {
		return x.ResponseValue
	}
	return ""
}

func (x *HistoryEntry) GetCreatedUnix() int64 {
	if x != nil {
		return x.CreatedUnix
	}
	return 0
}

func (x *HistoryEntry) GetCompletedUnix() int64 {
	if x != nil {
		return x.CompletedUnix
	}
	return 0
}

var File_proto_hermes_proto protoreflect.FileDescriptor

const file_proto_hermes_proto_rawDesc = "" +
	"\n" +
	"\x12proto/hermes.proto\x12\x06hermes\"@\n" +
	"\rNotifyRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vconfig_json\x18\x02 \x01(\fR\n" +
	"configJson\"Y\n" +
	"\x0eNotifyResponse\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\x12\x1b\n" +
	"\texit_code\x18\x02 \x01(\x05R\bexitCode\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"=\n" +
	"\x12GetUIConfigRequest\x12'\n" +
	"\x0fnotification_id\x18\x01 \x01(\tR\x0enotificationId\"a\n" +
	"\x13GetUIConfigResponse\x12\x1f\n" +
	"\vconfig_json\x18\x01 \x01(\fR\n" +
	"configJson\x12)\n" +
	"\x10deferral_allowed\x18\x02 \x01(\bR\x0fdeferralAllowed\"T\n" +
	"\x13ReportChoiceRequest\x12'\n" +
	"\x0fnotification_id\x18\x01 \x01(\tR\x0enotificationId\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"2\n" +
	"\x14ReportChoiceResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\"8\n" +
	"\rCancelRequest\x12'\n" +
	"\x0fnotification_id\x18\x01 \x01(\tR\x0enotificationId\"&\n" +
	"\x0eCancelResponse\x12\x14\n" +
	"\x05found\x18\x01 \x01(\bR\x05found\"\r\n" +
	"\vListRequest\"N\n" +
	"\fListResponse\x12>\n" +
	"\rnotifications\x18\x01 \x03(\v2\x18.hermes.NotificationInfoR\rnotifications\"\xbb\x01\n" +
	"\x10NotificationInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\aheading\x18\x02 \x01(\tR\aheading\x12\x14\n" +
	"\x05state\x18\x03 \x01(\tR\x05state\x12\x1f\n" +
	"\vdefer_count\x18\x04 \x01(\x05R\n" +
	"deferCount\x12#\n" +
	"\rdeadline_unix\x18\x05 \x01(\x03R\fdeadlineUnix\x12!\n" +
	"\fcreated_unix\x18\x06 \x01(\x03R\vcreatedUnix\"\x14\n" +
	"\x12ListHistoryRequest\"E\n" +
	"\x13ListHistoryResponse\x12.\n" +
	"\arecords\x18\x01 \x03(\v2\x14.hermes.HistoryEntryR\arecords\"\xdb\x01\n" +
	"\fHistoryEntry\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\aheading\x18\x02 \x01(\tR\aheading\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x16\n" +
	"\x06source\x18\x04 \x01(\tR\x06source\x12%\n" +
	"\x0eresponse_value\x18\x05 \x01(\tR\rresponseValue\x12!\n" +
	"\fcreated_unix\x18\x06 \x01(\x03R\vcreatedUnix\x12%\n" +
	"\x0ecompleted_unix\x18\a \x01(\x03R\rcompletedUnix2\x8f\x03\n" +
	"\rHermesService\x127\n" +
	"\x06Notify\x12\x15.hermes.NotifyRequest\x1a\x16.hermes.NotifyResponse\x12F\n" +
	"\vGetUIConfig\x12\x1a.hermes.GetUIConfigRequest\x1a\x1b.hermes.GetUIConfigResponse\x12I\n" +
	"\fReportChoice\x12\x1b.hermes.ReportChoiceRequest\x1a\x1c.hermes.ReportChoiceResponse\x127\n" +
	"\x06Cancel\x12\x15.hermes.CancelRequest\x1a\x16.hermes.CancelResponse\x121\n" +
	"\x04List\x12\x13.hermes.ListRequest\x1a\x14.hermes.ListResponse\x12F\n" +
	"\vListHistory\x12\x1a.hermes.ListHistoryRequest\x1a\x1b.hermes.ListHistoryResponseB*Z(github.com/TsekNet/hermes/proto/hermespbb\x06proto3"

var (
	file_proto_hermes_proto_rawDescOnce sync.Once
	file_proto_hermes_proto_rawDescData []byte
)

func file_proto_hermes_proto_rawDescGZIP() []byte {
	file_proto_hermes_proto_rawDescOnce.Do(func() {
		file_proto_hermes_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_hermes_proto_rawDesc), len(file_proto_hermes_proto_rawDesc)))
	})
	return file_proto_hermes_proto_rawDescData
}

var file_proto_hermes_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_proto_hermes_proto_goTypes = []any{
	(*NotifyRequest)(nil),        // 0: hermes.NotifyRequest
	(*NotifyResponse)(nil),       // 1: hermes.NotifyResponse
	(*GetUIConfigRequest)(nil),   // 2: hermes.GetUIConfigRequest
	(*GetUIConfigResponse)(nil),  // 3: hermes.GetUIConfigResponse
	(*ReportChoiceRequest)(nil),  // 4: hermes.ReportChoiceRequest
	(*ReportChoiceResponse)(nil), // 5: hermes.ReportChoiceResponse
	(*CancelRequest)(nil),        // 6: hermes.CancelRequest
	(*CancelResponse)(nil),       // 7: hermes.CancelResponse
	(*ListRequest)(nil),          // 8: hermes.ListRequest
	(*ListResponse)(nil),         // 9: hermes.ListResponse
	(*NotificationInfo)(nil),     // 10: hermes.NotificationInfo
	(*ListHistoryRequest)(nil),   // 11: hermes.ListHistoryRequest
	(*ListHistoryResponse)(nil),  // 12: hermes.ListHistoryResponse
	(*HistoryEntry)(nil),         // 13: hermes.HistoryEntry
}
var file_proto_hermes_proto_depIdxs = []int32{
	10, // 0: hermes.ListResponse.notifications:type_name -> hermes.NotificationInfo
	13, // 1: hermes.ListHistoryResponse.records:type_name -> hermes.HistoryEntry
	0,  // 2: hermes.HermesService.Notify:input_type -> hermes.NotifyRequest
	2,  // 3: hermes.HermesService.GetUIConfig:input_type -> hermes.GetUIConfigRequest
	4,  // 4: hermes.HermesService.ReportChoice:input_type -> hermes.ReportChoiceRequest
	6,  // 5: hermes.HermesService.Cancel:input_type -> hermes.CancelRequest
	8,  // 6: hermes.HermesService.List:input_type -> hermes.ListRequest
	11, // 7: hermes.HermesService.ListHistory:input_type -> hermes.ListHistoryRequest
	1,  // 8: hermes.HermesService.Notify:output_type -> hermes.NotifyResponse
	3,  // 9: hermes.HermesService.GetUIConfig:output_type -> hermes.GetUIConfigResponse
	5,  // 10: hermes.HermesService.ReportChoice:output_type -> hermes.ReportChoiceResponse
	7,  // 11: hermes.HermesService.Cancel:output_type -> hermes.CancelResponse
	9,  // 12: hermes.HermesService.List:output_type -> hermes.ListResponse
	12, // 13: hermes.HermesService.ListHistory:output_type -> hermes.ListHistoryResponse
	8,  // [8:14] is the sub-list for method output_type
	2,  // [2:8] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_proto_hermes_proto_init() }
func file_proto_hermes_proto_init() {
	if File_proto_hermes_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_hermes_proto_rawDesc), len(file_proto_hermes_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_hermes_proto_goTypes,
		DependencyIndexes: file_proto_hermes_proto_depIdxs,
		MessageInfos:      file_proto_hermes_proto_msgTypes,
	}.Build()
	File_proto_hermes_proto = out.File
	file_proto_hermes_proto_goTypes = nil
	file_proto_hermes_proto_depIdxs = nil
}
